# Generated by Django 3.0.6 on 2020-05-17 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='teacher_recruit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Sith'),
        ),
    ]
