# Generated by Django 3.0.6 on 2020-05-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200518_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='name_recruit',
            new_name='recruit',
        ),
    ]
