# Generated by Django 3.0.6 on 2020-05-18 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200518_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='first_question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='second_question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='third_question',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.TestShadowArm')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Question'),
        ),
    ]
